sa_louvre_homepage:
    path:     /
    defaults: { _controller: SALouvreBundle:Default:index }

sa_louvre_recap:
    path:     /recap
    defaults: { _controller: SALouvreBundle:Default:recap }
    
sa_louvre_checkout:
    path:     /checkout
    defaults: { _controller: SALouvreBundle:Default:checkout }
    
sa_louvre_success:
    path:     /success
    defaults: { _controller: SALouvreBundle:Default:success }


