services:
#    sa_louvre.example:
#        class: SA\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sa_louvre.calculatetarif:
        class: SA\LouvreBundle\Services\CalculateTarifs
#       arguments: ["@doctrine.orm.entity_manager"]

    sa_louvre.dayvalidator:
        class: SA\LouvreBundle\Validators\DayConstraintValidator
    
    sa_louvre.hourvalidator:
        class: SA\LouvreBundle\Validators\HourConstraintValidator
        
    sa_louvre.solddaysvalidator:
        class: SA\LouvreBundle\Validators\SoldDaysConstraintValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - name: validator.constraint_validator